export const mockData = {
  "version":2,
  "query":"java",
  "location":"austin, tx",
  "dupefilter":true,
  "highlight":false,
  "radius":25,
  "start":1,
  "end":10,
  "totalResults":547,
  "pageNumber":0,
  "results":[
      {
        "jobtitle":"Java Developer",
        "company":"XYZ Corp.,",
        "city":"Austin",
        "state":"TX",
        "country":"US",
        "formattedLocation":"Austin, TX",
        "source":"Dice",
        "date":"Mon, 02 Aug 2017 16:21:00 GMT",
        "snippet":"looking for an object-oriented Java Developer... Java Servlets...",
        "url":"https://www.indeed.com/viewjob?jk=12345&indpubnum=8343699265155203",
        "onmousedown":"indeed_clk(this, '0000');",
        "latitude":30.27127,
        "longitude":-97.74103,
        "jobkey":"12345",
        "sponsored":false,
        "expired":false,
        "indeedApply":true,
        "formattedLocationFull":"Austin, TX",
        "formattedRelativeTime":"11 hours ago"
      },
      {
        "jobtitle":"Node Developer",
        "company":"XYZ Corp.,",
        "city":"Austin",
        "state":"TX",
        "country":"US",
        "formattedLocation":"Austin, TX",
        "source":"Dice",
        "date":"Mon, 02 Aug 2017 16:21:00 GMT",
        "snippet":"looking for an object-oriented Java Developer... Java Servlets...",
        "url":"https://www.indeed.com/viewjob?jk=1232342345&indpubnum=8343699265155203",
        "onmousedown":"indeed_clk(this, '0000');",
        "latitude":30.27127,
        "longitude":-97.74103,
        "jobkey":"1232342345",
        "sponsored":false,
        "expired":false,
        "indeedApply":true,
        "formattedLocationFull":"Austin, TX",
        "formattedRelativeTime":"11 hours ago"
      },
      {
        "jobtitle":"Go Developer",
        "company":"XYZ Corp.,",
        "city":"Austin",
        "state":"TX",
        "country":"US",
        "formattedLocation":"Austin, TX",
        "source":"Dice",
        "date":"Mon, 02 Aug 2017 16:21:00 GMT",
        "snippet":"looking for an object-oriented Java Developer... Java Servlets...",
        "url":"https://www.indeed.com/viewjob?jk=5645645&indpubnum=8343699265155203",
        "onmousedown":"indeed_clk(this, '0000');",
        "latitude":30.27127,
        "longitude":-97.74103,
        "jobkey":"5645645",
        "sponsored":false,
        "expired":false,
        "indeedApply":true,
        "formattedLocationFull":"Austin, TX",
        "formattedRelativeTime":"11 hours ago"
      },
      {
        "jobtitle":"Ruby Developer",
        "company":"ABC Corp.,",
        "city":"Houston",
        "state":"TX",
        "country":"US",
        "formattedLocation":"Houston, TX",
        "source":"Dice",
        "date":"Mon, 02 Aug 2017 16:21:00 GMT",
        "snippet":"looking for an OOP JS Developer... Java Servlets...",
        "url":"https://www.indeed.com/viewjob?jk=123423&indpubnum=8343699265155203",
        "onmousedown":"indeed_clk(this, '0000');",
        "latitude":29.27127,
        "longitude":-87.74103,
        "jobkey":"123423",
        "sponsored":false,
        "expired":false,
        "indeedApply":true,
        "formattedLocationFull":"Houston, TX",
        "formattedRelativeTime":"23 hours ago"
    }
  ]
}